import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarComponent from "./NavbarComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// bisa juga untuk returnnya itu loadGetInitialProps, pake interface atau pake type
// ini penjelsannya
// https://chatgpt.com/c/69523eab-582c-8320-baed-ee1719c3f973
type Test1 = {
  children: React.ReactNode;
};

// atau pake interface

interface Test2 {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* nah disini itu adalah ayout untuk semua file kita yang ada di website ini */}
        {/* nah children ini adalah seluruh file page yang ada di projek ini lengkap  
          dengan layoutnya masing masing
          
          misal di about ada file page dan layout, page di file itu akna masuk ke layout
          dan nanti layoutnya yang akan menjadi childern disini, dan sleuruhnya
          untuk semua page dan layout pada folder masing masing*/}

          {/* ini penjelasannya https://chatgpt.com/c/695241f3-2acc-8321-83e5-2eae896bd9fb */}
          <NavbarComponent></NavbarComponent>
        {/* <header>Ini Header Layout App</header> */}
        {children}
        <footer>Ini Foouter Layout App</footer>
      </body>
    </html>
  );
}
