"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavbarComponent from "./NavbarComponent";
import "./globals.css";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// meta data itu gaboleh di taruh di compoennt client _> taid kan kita udah pake use client
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// bisa juga untuk returnnya itu loadGetInitialProps, pake interface atau pake type
// ini penjelsannya
// https://chatgpt.com/c/69523eab-582c-8320-baed-ee1719c3f973
type Test1 = {
  children: React.ReactNode;
};

// atau pake interface

interface Test2 {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // ingat kalo di next js itu syarat si hook itu harus berada didala component

  const pathName = usePathname();
  const hideNavbar = ['/login', '/register']
  // const [counter, setCounter] = useState(0);
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* nah disini itu adalah ayout untuk semua file kita yang ada di website ini */}
        {/* nah children ini adalah seluruh file page yang ada di projek ini lengkap  
          dengan layoutnya masing masing
          
          misal di about ada file page dan layout, page di file itu akna masuk ke layout
          dan nanti layoutnya yang akan menjadi childern disini, dan sleuruhnya
          untuk semua page dan layout pada folder masing masing*/}

        {/* ini penjelasannya https://chatgpt.com/c/695241f3-2acc-8321-83e5-2eae896bd9fb */}

        {/* nah ini juga sekalian ya, jaid sya iut maunya ketika saya lagi ada di /login atau /register saya itu ga mau nampilin navbarnya, nah gimana carnaya, caranya adalh lia aja di layout di root */}
        {/* {pathName != "/login" &&  pathName != "/register" ? (
          <NavbarComponent></NavbarComponent>
        ) : (
          <></>
        )} */}

        {/* lebih baik pake cara ini */}
          {
            // jadi kalo path namena itu enga ada di var hidenavbar maka liatin navbar
            !hideNavbar.includes(pathName) && <NavbarComponent/>
          }



        {/* <header>Ini Header Layout App</header> */}

        {/* ini contoh aja */}
        {/* nah dia tidak akna ilang statenya untuk disetiap seluruh halaman anaknya yang pake root / */}
        {/* ini ga bisa */}
        {/* <button onClick={() => setCounter(counter + 1)}>{counter}</button> */}
        {/* ini adalah si layoutabout */}
        {children}
        <footer>Ini Foouter Layout App</footer>
      </body>
    </html>
  );
}
